### ISSUE TITLE
Problema de fecha

### ISSUE THREAD

**Issue by ominec** [ominec/elahorro2.0#1]
La fecha de emisión de las faacturas se queda estático por ejemplo, la factura creada a las 21:00 horas tiene 
![image.png](https://images.zenhubusercontent.com/5aef0e644b5806bc2bd1ed79/5f5c5753-d6a2-4889-9381-8c1ecb7d5b7b)![image.png]
Otro documento (pedido) creado pasado las 00:00 tiene la misma fecha 
![image.png](https://images.zenhubusercontent.com/5aef0e644b5806bc2bd1ed79/171267db-473e-44cb-b923-c211926fe39d)
Cuando se crea la factura 
![image.png](https://images.zenhubusercontent.com/5aef0e644b5806bc2bd1ed79/d33bc01e-349e-405d-8abf-aeb6b2153975)
Pedido de las 6 de la mañana
![image.png](https://images.zenhubusercontent.com/5aef0e644b5806bc2bd1ed79/bd8bbdfa-1b2c-422b-a5c1-8739bc29ca68)
Factura
![image.png](https://images.zenhubusercontent.com/5aef0e644b5806bc2bd1ed79/e9afb6a4-8548-436a-bdda-9c87d882cb83)

**Comment by arkhan3x** [comment]
en el commit 48831478dd5e08a9d861527d15e81c576bc8f451 se cambia la lógica para obtener el valor del campo date_order_local, y se hace que el campo se recalcule en base al campo date_order, por favor revisar.
