### ISSUE TITLE
Demora en el reporte de rotación de stock

### ISSUE THREAD

**Issue by ominec** [ominec/elahorro2.0#2]
Cuando se ejecuta el reporte de rotación de stock por cada bodega se demora alrededor de 30 minutos, para sacar el reporte de los 8 locales no se culminado, por el tiempo.

![image.png](https://images.zenhubusercontent.com/5aef0e644b5806bc2bd1ed79/c543ae82-4284-4311-bff4-e62ff0eba42c)

Es por tal razón que se debe optimizar los tiempos. Como referencia el módulo de Stock tenia el mismo problema, lo que hizo Gaby es no utilizar el ORM de Odoo y mandar las consultas directas a la base de datos

**Comment by arkhan3x** [comment]
Se desarrollo un reporte nuevo para solventar ese problema
