### ISSUE TITLE
Agregar columnas al reporte de rotación de stock

### ISSUE THREAD

**Issue by ominec** [ominec/elahorro2.0#3]
En el reporte de rotación de stock agregar tres columnas: Proveedor, Categoría del producto y Tipo de producto.

![image.png](https://images.zenhubusercontent.com/5aef0e644b5806bc2bd1ed79/75dfafd2-bd4e-48af-9db5-b4d550b6e153)

**Comment by arkhan3x** [comment]
Cerrado con issue #2
