### ISSUE TITLE
Pasar el reporte de rotación de stock a español

### ISSUE THREAD

**Issue by ominec** [ominec/elahorro2.0#4]
![image.png](https://images.zenhubusercontent.com/5aef0e644b5806bc2bd1ed79/cd0ebaba-b125-4d3f-ba6c-80ea70970f67)

![image.png](https://images.zenhubusercontent.com/5aef0e644b5806bc2bd1ed79/639725c3-3455-4f38-9f66-1f897f862c14)

**Comment by arkhan3x** [comment]
Cerrado con issue #2
